# 77. GitHub Actions and Argos CI - added argos.yml to create the Argos build at https://app.argos-ci.com/jcrossland87
# Updated argos.yml in Copilot. ARGOS_TOKEN from https://app.argos-ci.com/jcrossland87/pw-practice-app/settings/authentication
# Copied ARGOS_TOKEN into GitHub Actions Secrets https://github.com/jcrossland87/pw-practice-app/settings/secrets/actions

name: Argos

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  argos:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm ci --force
      - run: npx playwright install --with-deps --force
      - run: npm run pageObjects-chrome